# Generated by Django 5.2.8 on 2025-11-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("IT", "Information Technology"),
                            ("HR", "Human Resources"),
                            ("Finance", "Finance"),
                            ("Marketing", "Marketing"),
                            ("Sales", "Sales"),
                        ],
                        max_length=50,
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_joined", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-date_joined"],
            },
        ),
    ]
